use sqlx::PgPool;
use uuid::Uuid;

use crate::shared::errors::AppError;

use super::model::{
    AdminOwnerRequestDetailRow, AdminOwnerRequestRow, OwnerRequestRow, OwnerRequestStatus,
    ValidatedIdentityData,
};

fn db_err(error: sqlx::Error) -> AppError {
    AppError::Database(error.to_string())
}

/// Fast-fail check for the common case. Not the concurrency authority: two
/// concurrent submissions can both pass this and race on the INSERT, which
/// is why `insert_pending` also handles the unique-violation outcome.
pub async fn pending_exists_for_user(pool: &PgPool, user_id: Uuid) -> Result<bool, AppError> {
    sqlx::query_scalar!(
        r#"SELECT EXISTS(SELECT 1 FROM owner_requests WHERE user_id = $1 AND status = 'pending') AS "exists!""#,
        user_id
    )
    .fetch_one(pool)
    .await
    .map_err(db_err)
}

/// Writes `users.phone` and inserts the new pending request in one
/// transaction, so neither half lands without the other. `request_id` is
/// generated by the caller before this runs, so uploaded document keys are
/// already anchored to it. Callers are expected to have already uploaded
/// every document under `request_id` before calling this — on failure here,
/// the caller is responsible for deleting those now-orphaned uploads.
pub async fn insert_pending(
    pool: &PgPool,
    request_id: Uuid,
    user_id: Uuid,
    phone: &str,
    secondary_phone: Option<&str>,
    identity_data: serde_json::Value,
    identity_documents: serde_json::Value,
) -> Result<OwnerRequestRow, AppError> {
    let mut tx = pool.begin().await.map_err(db_err)?;

    sqlx::query!("UPDATE users SET phone = $2 WHERE id = $1", user_id, phone)
        .execute(&mut *tx)
        .await
        .map_err(db_err)?;

    let row = match sqlx::query_as!(
        OwnerRequestRow,
        r#"
        INSERT INTO owner_requests (id, user_id, phone, secondary_phone, identity_data, identity_documents)
        VALUES ($1, $2, $3, $4, $5, $6)
        RETURNING id, status AS "status: OwnerRequestStatus",
                  to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "created_at!",
                  to_char(reviewed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "reviewed_at",
                  admin_note
        "#,
        request_id,
        user_id,
        phone,
        secondary_phone,
        identity_data,
        identity_documents,
    )
    .fetch_one(&mut *tx)
    .await
    {
        Ok(row) => row,
        // Dropping `tx` un-committed rolls back the `users.phone` write too.
        Err(sqlx::Error::Database(db_error)) if db_error.is_unique_violation() => {
            return Err(AppError::OwnerRequestAlreadyPending)
        }
        Err(error) => return Err(db_err(error)),
    };

    tx.commit().await.map_err(db_err)?;
    Ok(row)
}

/// The caller's most recent request, if any — backs the status endpoint.
pub async fn find_current_for_user(
    pool: &PgPool,
    user_id: Uuid,
) -> Result<Option<OwnerRequestRow>, AppError> {
    sqlx::query_as!(
        OwnerRequestRow,
        r#"
        SELECT id, status AS "status: OwnerRequestStatus",
               to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "created_at!",
               to_char(reviewed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "reviewed_at",
               admin_note
        FROM owner_requests
        WHERE user_id = $1
        ORDER BY created_at DESC
        LIMIT 1
        "#,
        user_id
    )
    .fetch_optional(pool)
    .await
    .map_err(db_err)
}

/// Count of requests matching `status` (or every request, when `None`) —
/// paired with `list_for_admin` to build the pagination envelope.
pub async fn count_for_admin(
    pool: &PgPool,
    status: Option<OwnerRequestStatus>,
) -> Result<i64, AppError> {
    sqlx::query_scalar!(
        r#"
        SELECT COUNT(*) AS "count!"
        FROM owner_requests
        WHERE ($1::owner_request_status IS NULL OR status = $1)
        "#,
        status as Option<OwnerRequestStatus>,
    )
    .fetch_one(pool)
    .await
    .map_err(db_err)
}

/// One page of the admin queue, most recent first, optionally filtered by
/// `status`. Never selects `identity_data`/`identity_documents` — those
/// belong to a single applicant's own record, not to every row of a shared
/// list, and stay behind [`find_by_id_for_admin`].
pub async fn list_for_admin(
    pool: &PgPool,
    status: Option<OwnerRequestStatus>,
    limit: i64,
    offset: i64,
) -> Result<Vec<AdminOwnerRequestRow>, AppError> {
    sqlx::query_as!(
        AdminOwnerRequestRow,
        r#"
        SELECT
            orq.id,
            u.email,
            u.first_name,
            u.last_name,
            orq.phone,
            orq.secondary_phone,
            orq.status AS "status: OwnerRequestStatus",
            to_char(orq.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "created_at!",
            to_char(orq.reviewed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "reviewed_at",
            orq.admin_note
        FROM owner_requests orq
        JOIN users u ON u.id = orq.user_id
        WHERE ($1::owner_request_status IS NULL OR orq.status = $1)
        ORDER BY orq.created_at DESC
        LIMIT $2 OFFSET $3
        "#,
        status as Option<OwnerRequestStatus>,
        limit,
        offset,
    )
    .fetch_all(pool)
    .await
    .map_err(db_err)
}

/// One request's full detail, `identity_data`/`identity_documents` included —
/// the one place an admin can see them, fetched by id alone.
pub async fn find_by_id_for_admin(
    pool: &PgPool,
    request_id: Uuid,
) -> Result<Option<AdminOwnerRequestDetailRow>, AppError> {
    sqlx::query_as!(
        AdminOwnerRequestDetailRow,
        r#"
        SELECT
            orq.id,
            u.email,
            u.first_name,
            u.last_name,
            orq.phone,
            orq.secondary_phone,
            orq.identity_data AS "identity_data: sqlx::types::Json<ValidatedIdentityData>",
            orq.identity_documents,
            orq.status AS "status: OwnerRequestStatus",
            to_char(orq.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "created_at!",
            to_char(orq.reviewed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS "reviewed_at",
            orq.admin_note
        FROM owner_requests orq
        JOIN users u ON u.id = orq.user_id
        WHERE orq.id = $1
        "#,
        request_id,
    )
    .fetch_optional(pool)
    .await
    .map_err(db_err)
}
